---
name: simple-go-web-app

instance_groups:
- name: webapp
  azs: [z1, z2, z3]
  instances: 1
  vm_type: default
  stemcell: windows
  networks: [{name: default}]
  jobs:
  - name: simple-go-web-app
    release: sample-go-windows
    properties: {}

variables: []

stemcells:
- alias: windows
  os: windows2012R2
  version: latest

update:
  canaries: 1
  canary_watch_time: 1000-120000
  update_watch_time: 1000-120000
  max_in_flight: 1
  serial: false

releases:
- name: sample-go-windows
  version: latest
  # In future, for the benefit of users, please replace with final release URL/version/sha1:
  #
  # For example:
  # version: 0.1.0
  # url: https://github.com/cloudfoundry-community/sample-go-web-app-boshrelease/releases/download/v0.1.0/sample-go-web-app-0.1.0.tgz
  # sha1: d6b67ccc255c4d7019702573d829a7ff29fa0dc8
