---
name: simple-go-web-app

instance_groups:
- name: webapp
  azs: [z1, z2, z3]
  instances: 1
  vm_type: default
  stemcell: windows
  networks: [{name: default}]
  jobs:
  - name: simple-go-web-app
    release: sample-go-windows
    properties:
      port: 3000

variables: []

stemcells:
- alias: windows
  os: windows2016
  version: latest

update:
  canaries: 1
  canary_watch_time: 1000-120000
  update_watch_time: 1000-120000
  max_in_flight: 1
  serial: false

releases:
- name: sample-go-windows
  version: 0.1.0
  url: https://github.com/cloudfoundry-community/sample-go-windows-boshrelease/releases/download/v0.1.0/sample-go-windows-0.1.0.tgz
  sha1: 69d035d1079d6bfc1387039e49510508c2fe32cf
