---
name: simple-go-web-app

instance_groups:
- name: webapp
  azs: [z1, z2, z3]
  instances: 1
  vm_type: default
  stemcell: windows
  networks: [{name: default}]
  jobs:
  - name: simple-go-web-app
    release: sample-go-windows
    properties:
      port: 3000

variables: []

stemcells:
- alias: windows
  os: windows2016
  version: latest

update:
  canaries: 1
  canary_watch_time: 1000-120000
  update_watch_time: 1000-120000
  max_in_flight: 1
  serial: false

releases:
- name: sample-go-windows
  version: 1.0.0
  url: https://github.com/cloudfoundry-community/sample-go-windows-boshrelease/releases/download/v1.0.0/sample-go-windows-1.0.0.tgz
  sha1: 7d15b2bd43acf849fac5f6ec805e0b6cfa1b9bb5
